import type { ApiEndpoint } from './types';

export const API_CATALOG: readonly ApiEndpoint[] = [
  {
    id: 'batch-preview',
    name: 'Stock Polling',
    method: 'POST',
    path: '/api/biz/pay/batch-preview',
    description: 'Poll stock/soldOut status for all product tiers',
    hasBody: true,
    bodyTemplate: { invitationCode: '' },
  },
  {
    id: 'preview',
    name: 'Submit Order',
    method: 'POST',
    path: '/api/biz/pay/preview',
    description: 'Create payment order (requires captcha)',
    hasBody: true,
    bodyTemplate: {
      productId: 'product-5643e6',
      invitationCode: '',
      ticket: '<captcha_ticket>',
      randstr: '<captcha_randstr>',
    },
    note: 'Requires valid Tencent captcha ticket + randstr',
    errorCodes: [
      { code: 500, meaning: 'Invalid captcha ticket' },
      { code: 555, meaning: 'Server busy' },
      { code: 510000, meaning: 'Risk control triggered' },
      { code: 510001, meaning: 'Risk control triggered' },
      { code: 560, meaning: 'Identity verification required' },
    ],
  },
  {
    id: 'check',
    name: 'Payment Status',
    method: 'GET',
    path: '/api/biz/pay/check?bizId=<bizId>',
    description: 'Check if payment completed (poll every 1s)',
    hasBody: false,
    bodyTemplate: null,
  },
  {
    id: 'getCustomerInfo',
    name: 'User Info',
    method: 'GET',
    path: '/api/biz/customer/getCustomerInfo',
    description: 'Get current user profile and org info',
    hasBody: false,
    bodyTemplate: null,
  },
  {
    id: 'subscription-list',
    name: 'Subscription List',
    method: 'GET',
    path: '/api/biz/subscription/list',
    description: 'Get subscription status and plan details',
    hasBody: false,
    bodyTemplate: null,
  },
  {
    id: 'productIdInfo',
    name: 'Product ID Mapping',
    method: 'GET',
    path: '/api/biz/tokenResPack/productIdInfo',
    description: 'Map product names to SKU IDs',
    hasBody: false,
    bodyTemplate: null,
  },
  {
    id: 'happyNewYear',
    name: 'Activity Info',
    method: 'GET',
    path: '/api/biz/pay/happyNewYear',
    description: 'Get promotional activity information',
    hasBody: false,
    bodyTemplate: null,
  },
] as const;
