import type { ApiEndpoint } from './types';

export const API_CATALOG: readonly ApiEndpoint[] = [
  {
    id: 'batch-preview',
    name: 'Probe Stock',
    method: 'POST',
    path: '/api/biz/pay/batch-preview',
    description: 'Read-only probe: returns 9 product tiers with soldOut flags. Called on page load and during war-time stock-flip polling.',
    role: 'Probe',
    hasBody: true,
    bodyTemplate: { invitationCode: '' },
  },
  {
    id: 'subscription-detail',
    name: 'User Subscription State',
    method: 'GET',
    path: '/api/biz/subscription/enterprise/v2/subscription/detail',
    description: 'Route key: returns hasSubscription and userState, which decides whether the next step uses new-purchase or comeback/upgrade paths.',
    role: 'Route',
    hasBody: false,
    bodyTemplate: null,
  },
  {
    id: 'comeback-check',
    name: 'Comeback Route Check',
    method: 'GET',
    path: '/api/biz/pay/comeback/check',
    description: 'Route key: returns userState and targetProductId for old users considering a comeback purchase.',
    role: 'Route',
    hasBody: false,
    bodyTemplate: null,
  },
  {
    id: 'getCustomerInfo',
    name: 'Customer Profile',
    method: 'GET',
    path: '/api/biz/customer/getCustomerInfo',
    description: 'Informational: returns current user profile, customerId and org/project info.',
    role: 'Informational',
    hasBody: false,
    bodyTemplate: null,
  },
  {
    id: 'subscription-list',
    name: 'Subscription List',
    method: 'GET',
    path: '/api/biz/subscription/list',
    description: 'Informational: returns subscription status and plan details.',
    role: 'Informational',
    hasBody: false,
    bodyTemplate: null,
  },
  {
    id: 'productIdInfo',
    name: 'Product ID Mapping',
    method: 'GET',
    path: '/api/biz/tokenResPack/productIdInfo',
    description: 'Informational: maps product names to SKU IDs.',
    role: 'Informational',
    hasBody: false,
    bodyTemplate: null,
  },
  {
    id: 'preview',
    name: 'Reserve Stock',
    method: 'POST',
    path: '/api/biz/pay/preview',
    description: 'Reserve: allocates a bizId and locks stock. The first mutating step in the new-purchase chain; requires a valid Tencent captcha ticket.',
    role: 'Reserve',
    hasBody: true,
    bodyTemplate: {
      productId: 'product-5643e6',
      invitationCode: '',
      ticket: '<captcha_ticket>',
      randstr: '<captcha_randstr>',
    },
    note: 'Requires valid Tencent captcha ticket + randstr',
    errorCodes: [
      { code: 500, meaning: 'Invalid captcha ticket' },
      { code: 555, meaning: 'Server busy' },
      { code: 510000, meaning: 'Risk control triggered' },
      { code: 510001, meaning: 'Risk control triggered' },
      { code: 560, meaning: 'Identity verification required' },
    ],
  },
  {
    id: 'comeback-preview',
    name: 'Reserve Stock (Comeback)',
    method: 'POST',
    path: '/api/biz/pay/comeback/preview',
    description: 'Reserve: old-user comeback variant of pay/preview. Only used when userState is ACTIVE_V1_CODING_PLAN_WITHOUT_AUTO_RENEW, MISTAKEN_UPGRADE or EXPIRED_V1_CODING_PLAN.',
    role: 'Reserve',
    hasBody: true,
    bodyTemplate: {
      productId: '<targetProductId>',
      invitationCode: '',
      ticket: '<captcha_ticket>',
      randstr: '<captcha_randstr>',
    },
    note: 'Only called for comeback-eligible user states',
  },
  {
    id: 'create-sign',
    name: 'Commit Payment',
    method: 'POST',
    path: '/api/biz/pay/create-sign',
    description: 'Commit: consumes the bizId from pay/preview and generates the Alipay/WeChat payment sign URL plus orderId.',
    role: 'Commit',
    hasBody: true,
    bodyTemplate: {
      productId: '<productId>',
      customerId: '<customerId>',
      bizId: '<bizId>',
      payType: 'ALI',
      invitationCode: '',
    },
  },
  {
    id: 'product-update-sign',
    name: 'Commit Payment (Upgrade)',
    method: 'POST',
    path: '/api/biz/pay/product/update/sign',
    description: 'Commit: upgrade/renewal variant of create-sign. Only used when isSubscribeLocal===true (existing subscription).',
    role: 'Commit',
    hasBody: true,
    bodyTemplate: {
      oldProductId: '<oldProductId>',
      newProductId: '<newProductId>',
      customerId: '<customerId>',
      agreementNo: '<agreementNo>',
      bizId: '<bizId>',
    },
    note: 'Only called for renewals/upgrades',
  },
  {
    id: 'check',
    name: 'Poll Payment Status',
    method: 'GET',
    path: '/api/biz/pay/check?bizId=<bizId>',
    description: 'Poll: read-only 1-second polling after create-sign. Returns SUCCESS, PENDING or EXPIRE.',
    role: 'Poll',
    hasBody: false,
    bodyTemplate: null,
  },
] as const;
