#!/usr/bin/env node
/**
 * Build bm-main.js from modular source files.
 * Reads public/bm-main/00-*.js through 08-*.js in order,
 * wraps them in an IIFE, and outputs to public/bm-main.js.
 */
const fs = require('fs');
const path = require('path');

const SRC_DIR = path.join(__dirname, '..', 'src', 'bm-main');
const OUT_FILE = path.join(__dirname, '..', 'public', 'bm-main.js');

// Read all module files in sorted order
const files = fs.readdirSync(SRC_DIR)
  .filter(f => f.endsWith('.js'))
  .sort();

if (files.length === 0) {
  console.error('No module files found in', SRC_DIR);
  process.exit(1);
}

// Read content of each module
const modules = files.map(f => {
  const content = fs.readFileSync(path.join(SRC_DIR, f), 'utf8');
  return `// ── ${f} ──\n${content}`;
});

// Wrap in IIFE
const output = `// MAIN world script — full Prod UI overlay on bigmodel.cn
// AUTO-GENERATED by scripts/build-overlay.js — DO NOT EDIT DIRECTLY
(function() {
  if (window.__bmPaymentIntercept) return;
  window.__bmPaymentIntercept = true;

${modules.join('\n\n')}

})();
`;

fs.writeFileSync(OUT_FILE, output, 'utf8');
console.log(`Built ${OUT_FILE} from ${files.length} modules (${(output.length / 1024).toFixed(1)}KB)`);
